'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G/cUBW3W5mNRrGNKKGpddQ==")>  _
        Public Property PublicKey() As String
            Get
                Return CType(Me("PublicKey"),String)
            End Get
            Set
                Me("PublicKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1zb7U!53=e1L]7JI[Uv3fz,zwc3s4E")>  _
        Public Property EncryptKey() As String
            Get
                Return CType(Me("EncryptKey"),String)
            End Get
            Set
                Me("EncryptKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("uEUOqyST52v2XxOV3Le-0wKvhtdrfGLsDnLCXotTerzwITKmY87xn8ATnM3ZnQgzRHM2N66gV4qEq1mAt"& _ 
            "7pSs__0XKXbp9PMrsjTWKYpltMT50upx34dRCOTn-AZJL3J7HE1NzQzEE603tIlNdw85zAMSRHKVG3q1"& _ 
            "cDScgVepwV0Efo3COYkE3RAN8lxyVCMrh6a-LdogpcvGP8buUCo335og13DiIH78Gnpn45x2XnvCzn_s"& _ 
            "rYxUEwKineugQzDgRwh4KIkEXl_T1PLk0FfZQ4eZAV9LrHUIa4FZiYgQKUeHvY4um4hS8JFcYkcyAHk_"& _ 
            "B0m-547jx9AneordiFLQqDdXbSlXAnM6Vhl7qaoKbiPqxhLwdfruL2tdrWp8Oc4T6YIF1ppX_4H62MLX"& _ 
            "LXtppaSU3aHdO_n_naD0HW0NqcOdED7vVv0WiZFka-ek2_-a1E642CIU87rOpA0KltGXvIZivCjMCIRH"& _ 
            "9w3us4arLg")>  _
        Public Property AccessToken() As String
            Get
                Return CType(Me("AccessToken"),String)
            End Get
            Set
                Me("AccessToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1295999")>  _
        Public Property Expiration() As String
            Get
                Return CType(Me("Expiration"),String)
            End Get
            Set
                Me("Expiration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cccubed")>  _
        Public Property User() As String
            Get
                Return CType(Me("User"),String)
            End Get
            Set
                Me("User") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Mon, 13 Jul 2015 05:44:27 GMT")>  _
        Public Property Issued() As String
            Get
                Return CType(Me("Issued"),String)
            End Get
            Set
                Me("Issued") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tue, 28 Jul 2015 05:44:27 GMT")>  _
        Public Property Expires() As String
            Get
                Return CType(Me("Expires"),String)
            End Get
            Set
                Me("Expires") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Chevon.My.MySettings
            Get
                Return Global.Chevon.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
